### ISSUE TITLE
Where is the original repo?

### ISSUE THREAD

**Issue by leonixyz** [m4chinations/self-destructing-cookies#1]
Hi, 

I wasn't able to find the original repository for this add on.

Where did you forked it?

Regards

**Comment by m4chinations** [comment]
Hey @leonixyz, 

As with most Firefox addons, you can always get the original source from their AMO version page. https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/versions/ 

I don't think the original author has put the code anywhere on Github.
